---

- hosts: all
  become: true                      # execute as sudo
  pre_tasks:                        # pre_tasks always be run first

  - name: install update (CentOS)
    tags: always                    # run this tag alway
    dnf: 
      # update_only: yes
      update_cache: yes
    changed_when: false             # 
    when: ansible_distribution == "CentOS"

  - name: install update (Ubuntu)
    tags: always
    apt: 
      # upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"



- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers






